import numpy as np
var = np.array([1, 2, 3, 4, 12, 13, 14, 15])
#print("Data Type: ", var.dtype)
var1 = np.array([1.0, 1.2, 1.3])
#print("Data Type:", var1.dtype)
var2 = np.array(["A", "S", "D", "F"])
#print("Data Type:", var2.dtype)
var3 = np.array(["A", "S", "D", "F", 1, 2, 3, 4])
#print("Data Type:", var3.dtype)
x = np.array([1, 2, 3, 4], dtype=np.int8)
#print("Data Type:", x.dtype)
#print(x)

x1 = np.array([1, 2, 3, 4], dtype="f")
#print("Data Type:", x.dtype)
#print(x1)

x2 = np.array([1, 2, 3, 4])
new = np.float32(x2)
new_one = np.int_(new)
#print("Data Type:", x2.dtype)
#print("Data Type:", new.dtype)
#print("Data Type:", new_one.dtype)
#print(x2)
#print(new)
#print(new_one)

x3 = np.array([1, 2, 3, 4])
new_l = x3.astype(float)
print(x3)
print(new_l)